### ISSUE TITLE
Could not load PC BIOS:'/usr/share/edk2-ovmf/x64/OVMF_CODE.fd'

### ISSUE THREAD

**Issue by ToasterGithubUser** [royalgraphx/LegacyOSXKVM#1]
why this happening im installing snow leopard

**Comment by royalgraphx** [comment]
This is a host related issue, if you have not installed the OVMF package, you must do so, that information could've been googled for a quicker response, this is a general and incredibly incredibly common qemu/host related issue, not related to the repository at all. In fact, I included OVMF there, you can easily change the path to use it.

**Comment by ToasterGithubUser** [comment]
thanks a lot now its working
