### ISSUE TITLE
10.1 link broken

### ISSUE THREAD

**Issue by kingbuzzman** [royalgraphx/LegacyOSXKVM#5]
Getting a 404 on 10.1 download link

**Comment by royalgraphx** [comment]
This project in general has been deprecated per the README, but be on the look out for a commit coming to both [DarwinKVM](https://github.com/royalgraphx/DarwinKVM) and [DarwinFetch](https://github.com/royalgraphx/DarwinFetch) which adds full support for PowerPC and Intel releases for 10.0 - 10.6, it's been a big thing coming for a while now, the merge has been declared for months so be on the look out possibly today or tomorrow for that commit. 🙏🏻
