### ISSUE TITLE
Booting SL on Silicon mac

### ISSUE THREAD

**Issue by startergo** [royalgraphx/LegacyOSXKVM#8]
Do you have by any chance the config file for AS and SL?
A user is not able to boot it in QEMU (or UTM)
https://forums.macrumors.com/threads/install-snow-leopard-in-qemu-and-utm.2425916/post-33165988

**Comment by royalgraphx** [comment]
The README states this project is deprecated, and did you even read far enough to clearly see where I explain how to boot SL on AS?
